# Site settings
title: Drew Douglass
email: drew@creatingdrew.com
description: > # this means to ignore newlines until "baseurl:"
  Code, web projects, libraries, and links to my other work. 
  &copy; 2016 Drew Douglass
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://drewdouglass.github.io" # the base hostname & protocol for your site
twitter_username: DrewDouglass
github_username:  DrewDouglass

# Build settings
markdown: kramdown

#Permalinks
permalink: /:title
